### ISSUE TITLE
The transfer task is preparing...

### ISSUE THREAD

**Issue by justhy** [Nenokkadine/ICopy-Heroku#1]
The transfer task is preparing...
The transfer task has been preparing...

**Comment by Nenokkadine** [comment]
Check your Rclone.conf and Conf.toml Once again

**Comment by Nenokkadine** [comment]
Actually I forget to change one thing now Updated it
Just change the flag in  conf.toml from --log-file=/root/icopy_cloner_debug.log to --log-file=/app/icopy_cloner_debug.log'
